# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - decamap-auth

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # Set yarn version
          # This line might vary based on the method you're using to install Yarn (npm or directly)
          # Here's an example using npm to install a specific Yarn version
          # Change the version number as per your requirement
          # You might need to modify this depending on your actual setup for Yarn installation
          # You could also use yarn directly if it's available in the environment
          run: npm install -g yarn@1.22.19

      - name: Install dependencies
        run: yarn install
      - name: yarn install, build, and test
        run: |
          yarn install
          yarn build 

      - name: Zip all files for upload between jobs
        run: zip --symlinks -r nest.zip ./*
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: nest.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip nest.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'decamap-auth'
          slot-name: 'Production'
          package:  nest.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6C68A2E5AE6D4186BD09D7231CB956D4 }}
          
      - name: Delete zip file
        run: rm nest.zip
